/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket */

#ifndef _Included_de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket
#define _Included_de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket
 * Method:    add
 * Signature: (J[[B)V
 */
JNIEXPORT void JNICALL Java_de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket_add
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket
 * Method:    connect
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket_connect
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket
 * Method:    disconnect
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket_disconnect
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket
 * Method:    bind
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket_bind
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket
 * Method:    unbind
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket_unbind
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket
 * Method:    setXPubVerbose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket_setXPubVerbose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket
 * Method:    shutdownNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_unistuttgart_isw_sfsc_commonjava_zmq_reactor_jni_JniReactiveSocket_shutdownNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
